run:
	g++ -o MIPS functions.cpp MIPS_simulator.cpp
	./MIPS 10 2 input5.txt

demo:
	g++ -o MIPS MIPS_simulator_demo.cpp
	./MIPS 2 5 input.txt

testing:
	g++ -o MIPS functions.cpp testing.cpp
	./MIPS 2 5 input1.txt

clean:
	rm -rf MIPS
